theme: jekyll-theme-cayman

title: MYDATA
description: Informational self-determination through data filtering and masking
use_breadcrumbs: true

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - name: "Home"
    link: ""
    icon: ""
  - name: "Policy Enforcement"
    link: "Einleitung"
    icon: ""
  - name: "Policy Language"
    link: "Anforderungen"
    icon: ""
  - name: "Central Services"
    link: "Realisierung"
    icon: ""
  - name: "Resources"
    link: "#resources"
    icon: ""