theme: jekyll-theme-cayman

title: MYDATA
description: Informational self-determination through data filtering and masking
use_breadcrumbs: true

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - name: "Home"
    link: ""
    icon: "/MYDATA/assets/images/house-solid.svg"
  - name: "Policy Enforcement"
    link: "Einleitung"
    icon: "/MYDATA/assets/images/bolt.svg"
  - name: "Policy Language"
    link: "Anforderungen"
    icon: "/MYDATA/assets/images/list-check.svg"
  - name: "Central Services"
    link: "Realisierung"
    icon: "/MYDATA/assets/images/gears.svg"
  - name: "Resources"
    link: "Bewertung"
    icon: "/MYDATA/assets/images/user-doctor.svg"