theme: jekyll-theme-cayman

title: MYDATA
description: Informational self-determination through data filtering and masking
use_breadcrumbs: false

plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - name: "Home"
    link: ""
    icon: "/MYDATA/assets/images/home.svg"
  - name: "Policy Enforcement"
    link: "sdk"
    icon: "/MYDATA/assets/images/toolbox.svg"
  - name: "Policy Language"
    link: "language"
    icon: "/MYDATA/assets/images/language.svg"
  - name: "Central Services"
    link: "services"
    icon: "/MYDATA/assets/images/layer-group.svg"
  - name: "Release Notes"
    link: "release-notes"
    icon: "/MYDATA/assets/images/code-commit.svg"
  - name: "Glossary"
    link: "glossary"
    icon: "/MYDATA/assets/images/spell-check.svg"